version: '3.5'

services:
  api:
    build:
      context: ./back
      dockerfile: "Dockerfile.dev"
    restart: always
    environment:
      - DB_HOST=${DB_HOST:-arsfestdb}
      - DB_USER=${DB_USER:-arsfest}
      - DB_PW=${DB_PW:-arsfest}
      - DB_NAME=${DB_NAME:-arsfest}
      - PORT=${APP_PORT:-5000}
      - INVITED_REG_OPENS=${INVITED_REG_OPENS:-9 February 2023 12:00}
      - INVITED_REG_CLOSES=${INVITED_REG_CLOSES:-17 February 2023 00:00}
      - NORMAL_REG_OPENS=${NORMAL_REG_OPENS:-20 February 2023 12:00}
      - NORMAL_REG_CLOSES=${NORMAL_REG_CLOSES:-12 March 2023 00:00}
      - PARTICIPANT_LIMIT=${PARTICIPANT_LIMIT:-235}
    container_name: arsfestapi
    depends_on:
      - db
    ports:
      - '5000:5000'
    networks:
      - db
      - api
    volumes:
      - type: bind
        source: ./back/src
        target: /opt/app/src

  ui:
    build:
      context: ./front
      dockerfile: "Dockerfile.dev"
    restart: always
    container_name: arsfestui
    depends_on:
      - db
      - api
    ports:
      - '8000:8000'
    networks:
      - api
    volumes:
      - type: bind
        source: ./front/src
        target: /opt/app/src

  db:
    container_name: arsfestdb
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-arsfest}
      - POSTGRES_PASSWORD=${DB_PW:-arsfest}      
      - POSTGRES_DB=${DB_NAME:-arsfest}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge
  api:
    driver: bridge
