POST http://localhost:5000/api/participant HTTP/1.1
content-type: application/json

{
    "namn": "kuk 5",
    "email": "kuk@gmail.com",
    "pris": 1000,
    "avec": "test avec",
    "sittplats": "Min kompis",
    "sillis": true,
    "solenn": true,
    "representerar": "tf",
    "alkohol": true,
    "meny": "kuk kött",
    "specialdieter": "Nej",
    "buss": true,
    "kommentarer": "Kakka",
    "visible": true
}
###
GET http://localhost:5000/api/participants HTTP/1.1
content-type: application/json
